version: '3'

services:
  elasticsearch-master:
    image: my-custom-elasticsearch-master:7.4.2
    build:
      context: ./
      dockerfile: Dockerfile.elasticsearch-master
    restart: on-failure
    container_name: elasticsearch-master
    ulimits: &elasticsearch-common-ulimits
      memlock:
        soft: -1
        hard: -1
    environment: &elasticsearch-common-env
      - ELASTICSEARCH_PLUGINS=analysis-icu,repository-gcs,discovery-gce
      - ELASTICSEARCH_HEAP_SIZE=512m
    # volumes:
      # - ./credential.json:/opt/bitnami/elasticsearch/config/credential.json
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  elasticsearch-data1:
    depends_on:
      - elasticsearch-master
    image: my-custom-elasticsearch-data:7.4.2
    build:
      context: ./
      dockerfile: Dockerfile.elasticsearch-data
    restart: on-failure
    container_name: elasticsearch-data1
    ulimits: *elasticsearch-common-ulimits
    environment: *elasticsearch-common-env
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - elastic

  elasticsearch-data2:  # optional
    depends_on:
      - elasticsearch-master
    image: my-custom-elasticsearch-data:7.4.2
    restart: on-failure
    container_name: elasticsearch-data2
    ulimits: *elasticsearch-common-ulimits
    environment: *elasticsearch-common-env
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    depends_on:
      - elasticsearch-master
    image: my-custom-kibana:7.4.2
    build:
      context: ./
      dockerfile: Dockerfile.kibana
    container_name: kibana
    restart: on-failure
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch-master
    ports:
      - "5601:5601"
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  plugin_volume:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
