FROM docker.io/bitnami/elasticsearch:7.4.2

COPY ./elasticsearch-master.yml /opt/bitnami/elasticsearch/config/elasticsearch.yml

RUN echo y | /opt/bitnami/elasticsearch/bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.4.2/elasticsearch-analysis-ik-7.4.2.zip

EXPOSE 9200 9300

USER 1001
ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "/run.sh" ]